### ISSUE TITLE
!h [argument] will send both a dm and instructions on the command

### ISSUE THREAD

**Issue by sirMerr** [sirMerr/camperbot#31]
## Bug Description

Using the help command with an argument triggers two messages instead of one.

## Screenshots/Code Links
(screenshots show different times because theyre two different instances)

<img width="582" alt="screen shot 2018-05-25 at 7 19 47 pm" src="https://user-images.githubusercontent.com/11183523/40543765-041c9bb8-6050-11e8-9c19-76cc59f6d96e.png">
<img width="625" alt="screen shot 2018-05-25 at 7 19 52 pm" src="https://user-images.githubusercontent.com/11183523/40543981-c7f1590c-6050-11e8-901e-8ef294e93041.png">

## Steps to Reproduce

1. Go in server
2. Enter `!h a`

**Comment by sirMerr** [comment]
After doing #26

**Comment by olegsmall** [comment]
It was fixed? Unable to reproduce
